name: ML_Project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - blas=1.0
  - bleach=6.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-libraries-dev=12.4.0
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.37
  - cuda-opencl-dev=12.6.37
  - cuda-profiler-api=12.6.37
  - cuda-runtime=12.4.0
  - cuda-version=12.6
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.6.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kaggle=1.6.17
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.2.65
  - libcublas-dev=12.4.2.65
  - libcufft=11.2.0.44
  - libcufft-dev=11.2.0.44
  - libcurand=10.3.7.37
  - libcurand-dev=10.3.7.37
  - libcusolver=11.6.0.99
  - libcusolver-dev=11.6.0.99
  - libcusparse=12.3.0.142
  - libcusparse-dev=12.3.0.142
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.2
  - libnpp-dev=12.2.5.2
  - libnvfatbin=12.6.20
  - libnvfatbin-dev=12.6.20
  - libnvjitlink=12.4.99
  - libnvjitlink-dev=12.4.99
  - libnvjpeg=12.3.1.89
  - libnvjpeg-dev=12.3.1.89
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.3
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-slugify=8.0.4
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-model-summary=0.1.1
  - pytorch-mutex=1.0
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - referencing=0.30.2
  - requests=2.32.3
  - rpds-py=0.10.6
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - text-unidecode=1.3
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=3.0.3
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torchaudio==2.4.0
      - torchvision==0.19.0
